---
- name: prepare dev node
  hosts: all
  become: yes
  
  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker.io
     state: present
  
  - name: Ensure python-pip is present
    apt:
     name: python3-pip
     state: present

  - name: docker.py
    pip:
     name: docker.py

  - name: Build an image 
    docker_image:
      path: /tmp
      name: tomcatbox

  - name: login dockerhub
    shell: docker login -u bitsl -p Kaluga123
    
  - name: create tag to image
    shell: docker tag tomcatbox bitsl/tomcatbox

  - name: push image on to dockerhub
    shell: docker push bitsl/tomcatbox
