---
- name: Ensure docker  is present
  apt:
   name: docker.io
   state: present
  
- name: Ensure python-pip is present
  apt:
   name: python3-pip
   state: present

- name: docker.py
  pip:
   name: docker.py

- name: Build an image 
  docker_image:
    build:
      path: ./Dev
    name: buildboxfuse
     
# - name:   docker build container boxfuse
#  docker_container:
#   name: buildboxfuse
#   image: buildboxfuse

- name:   docker  container boxfuse started
  docker_container:
   name: bulildboxfuse
   image: buildboxfuse
   state: started
