---
- name: Ensure docker  is present
    apt:
     name: docker.io
     state: present
  
  - name: Ensure python-pip is present
    apt:
     name: python3-pip
     state: present

  - name: docker.py
    pip:
     name: docker.py

  - name: Build an image 
    docker_image:
      path: /Dev
      name: buildbox
     
  - name:   docker  container boxfuse started
    docker_container:
     name: bulildbox
     image: buildbox
     state: started
