---
- name: Ensure docker  is present
  apt:
   name: docker.io
   state: present
  
- name: Ensure python-pip is present
  apt:
   name: python3-pip
   state: present

- name: docker.py
  pip:
   name: docker.py

- name:   docker  container tomcate started
  docker_container:
   name: tomcatbox1
   image: bitsl/tomcatbox1
   state: started
